### ISSUE TITLE
Simply loading and attempting to save an object fails validation

### ISSUE THREAD

**Issue by brightbytes** [mspanc/just-datetime-picker#11]
I followed the instructions for this gem and see the following at the Rails console:

1.9.3-p429 :001 > w = Webinar.first
  Webinar Load (0.9ms)  SELECT "webinars".* FROM "webinars" LIMIT 1
 => #<Webinar id: 1, scheduled_at: "2013-07-31 17:01:00", enabled: false, created_at: "2013-07-30 19:59:47", updated_at: "2013-07-30 20:25:07", presenter_id: 4> 
1.9.3-p429 :002 > w.save
   (0.2ms)  BEGIN
   (0.3ms)  ROLLBACK
 => false 
1.9.3-p429 :003 > w.errors.full_messages
 => ["Scheduled at date Invalid date", "Scheduled at Invalid date"] 

It seems like the process of loading a datetime field renders it invalid!

**Comment by mspanc** [comment]
Interesting bug, but I am not actively maintaining this gem anymore. It should be, however, quite easy to fix. Patches are welcome and would likely be merged into codebase.
