### ISSUE TITLE
Broken for rails 4 

### ISSUE THREAD

**Issue by ChrisGF** [mspanc/just-datetime-picker#14]
I love the idea of this gem.   I have a rails 4 app that I would love to use this with. Due to strong parameters I am unable to use it.

```
`attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one.
```

I know I can add in the protected_attributes gem but I would love to have an updated version that doesn't require this.

Thanks in advance for your help

**Comment by dharb** [comment]
The following worked for my rails 4.2 app:
add this to your app/admin/model.rb
```
permit_params :attribute, :attribute_date, :attribute_time_hour, :attribute_time_minute
```
add this to your app/models/model.rb
```
just_define_datetime_picker :attribute
```
