### ISSUE TITLE
how to let datetime-picker show date input only ?

### ISSUE THREAD

**Issue by songjiayang** [mspanc/just-datetime-picker#18]
i have tried to  change the column type from date time to date, but it does not work .

**Comment by ggrillone** [comment]
active admin has built-in support for just using a regular datepicker, if you don't need time to be included no point in using this particular gem

`f.input :date_field, as: :datepicker`

source: https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md#datepicker

**Comment by mspanc** [comment]
@ggrillone is right, it's a misuse of this gem.
