### ISSUE TITLE
Add support to add css class to the just_date_time fields

### ISSUE THREAD

**Issue by tommyalvarez** [mspanc/just-datetime-picker#20]
if using <%= f.input :field, as: :just_date_time_picker, input_html: {class: "myClass"} %>, the :class attr should make it into the 3 fields (date, hour and minute inputs).

**Comment by mspanc** [comment]
Hello, I am not actively maintaining this gem anymore. It should be, however, quite easy to add. Patches are welcome and would likely be merged into codebase.
