### ISSUE TITLE
Why I am not seeing the time section in the calendar?

### ISSUE THREAD

**Issue by millisami** [mspanc/just-datetime-picker#21]
I installed this following the Readme and its working.

But the time section is not shown in the Calendar?
And also clicking the time textbox, the calendar does not pops-up?
![screen shot 2014-09-03 at 7 16 43 pm](https://cloud.githubusercontent.com/assets/47914/4134650/b30bd778-336e-11e4-935e-2a148bb78999.png)

**Comment by walidvb** [comment]
The time is not meant to be displayed within the calendar, but rather next to it(as you see on your screenshot)

**Comment by mspanc** [comment]
Hello, this gem does not show time section in the calendar dialog. This is how it was designed.
