### ISSUE TITLE
Is this gem maintained anymore?

### ISSUE THREAD

**Issue by ggrillone** [mspanc/just-datetime-picker#22]
Looking at the last commit and going though the issues it seems the maintainer is no longer supporting this? Anyone know for a fact? Or if it's been forked somewhere? Thanks

**Comment by mecampbellsoup** [comment]
This gem doesn't seem necessary: http://activeadmin.info/docs/5-forms.html#datepicker

**Comment by mspanc** [comment]
Hi I am not using activeadmin in any of my active projects so I am no longer maintaining this gem but patches are welcome.

@mecampbellsoup the datepicker you've mentioned does not support time field.
