### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by besi** [mspanc/just-datetime-picker#26]
I have a property `ends_at` and I want to use the `just_datetime_picker` for it.

I got this working like so:

``` ruby
# My model
  def ends_at_time_hour=(h)
    minutes = self.ends_at.minute rescue nil
    self.ends_at = self.ends_at.change({hour: h.to_i, min: minutes}) rescue nil
  end

  def ends_at_time_hour
    self.ends_at.hour rescue nil
  end

  def ends_at_time_minute
    self.ends_at.minute rescue nil
  end

  def ends_at_time_minute=(m)
    self.ends_at = self.ends_at.change({min: m.to_i}) rescue nil
  end

  def ends_at_date
    self.ends_at.to_date rescue nil
  end

  def ends_at_date=(date)
    m = self.ends_at_time_minute
    h = self.ends_at_time_hour
    self.ends_at = date.to_datetime
    self.ends_at_time_hour = h if h.present?
    self.ends_at_time_minute = m if m.present?
  end
```

In `admin/my_model.rb` I need to make sure to permit those params:

``` ruby
  permit_params :title,
                #...
                :ends_at,
                :ends_at_date,
                :ends_at_time_minute,
                :ends_at_time_hour
```

**Comment by besi** [comment]
This is quite some extra effort and also a bit error prone. For example I have to set the `minutes` again in `ends_at_time_hour=` since setting the `hour` will clear the minutes.

Is there a way that the gem could handle this extra plumbing on the fly?

**Comment by besi** [comment]
The result:

![screenshot](https://cloud.githubusercontent.com/assets/160412/14331612/59f8ee62-fc46-11e5-8adf-fc857a59f64c.png)

**Comment by KacperPucek** [comment]
I have to say I had a little trouble understanding your code but if you don't want to do anything custom and just get it working it could be as follows.

```
#model
just_define_datetime_picker :end_at
```

```
# admin/model

# field in the form
f.input :end_at, as: :just_datetime_picker
#params
permit_params :end_at_date, :end_at_time_hour, :end_at_time_minute
```

If I'm missing something let me know and I'll see if I can help 👍

**Comment by besi** [comment]
Ok, my bad.
I did not realise that I have to add `just_define_datetime_picker :end_at` to my model.
